# ..travis.yml
#MIT License
#
#Copyright (c) 2018 CMPUT291PROJECTF18, CMPUT291F18MP2
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
language: python
os:
  - linux

stages:
  - lint
  - test
  - build
  - deploy


before_install:
  - pip install codecov
  - pip install pytest-cov


install:
  - pip install .["docs","tests"]


script:
  - py.test --cov-report=html --cov=mini_project_2 test/unit/
  - python setup.py test

after_success:
  - codecov


jobs:
  include:

    - python: 3.5
      dist: xenial
    - stage: lint
      python: 3.5
      script:
        - python setup.py lint || exit $(($? & 35))
    - stage: build
      python: 3.5
      script:
        - python setup.py sdist
    - stage: deploy
      name: "docs"
      python: 3.5
      script:
        - sphinx-build docs/ build/
